name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  dio: ^5.9.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analysis_options: any


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf  
    
        
       